name: Create GitHub Repository

on:
  workflow_dispatch:
    inputs:
      department_name:
        description: "The department name"
        required: true
      application_name:
        description: "The application name"
        required: true
      repo_name:
        description: "The repository name"
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Run Repository Creation Script
        run: |
          chmod +x ./scripts/create_repo.sh
          ./scripts/create_repo.sh "${{ github.event.inputs.department_name }}" "${{ github.event.inputs.application_name }}" "${{ github.event.inputs.repo_name }}"
