name: Automated Repository Creation

on:
  repository_dispatch:
    types: [repository_creation]

jobs:
  automated_repository_creation: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set execute permissions on the script
        run: chmod +x ./automate_repo_creation.sh
      - name: Run the shell script
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass the token from GitHub Secrets
        run: ./automate_repo_creation.sh "${{ github.event.client_payload.department_name }}" "${{ github.event.client_payload.application_name }}" "${{ github.event.client_payload.repo_name }}"